version: '3'

services:
  photo_slam:
    image: gloryh/photo-slam:v0.0.1
    container_name: photo_slam_container  
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - ./:/Photo-SLAM
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    tty: true
    stdin_open: true